### PR TITLE
Right adjoints in product category

### PR DESCRIPTION
**Pull request by stschaef**

### CODE REVIEW

**Comment by maxsnew** [comment]
Does anyone remember what this was for? Specifically, the `UnivEltProd` file, the other is self explanatory

**Comment by stschaef** [comment]
IIRC it was Eric's first pass at getting a universal element for the product presheaf. And then I came in later and try to generalize that construction as much as possible with the other file

I don't fully remember, but I think there was definitional differences between what he gave and what I made. Can't remember if they were reconcilable or not, can try to take a look at some point this week if you think its worth integrating both files

**Comment by stschaef** [comment]
@ericgiovannini did you ever need this?

**Comment by ericgiovannini** [comment]
> @ericgiovannini did you ever need this?

I haven't utilized it yet, but I expect that it will be useful for formulating limits in double categories

**Comment by maxsnew** [comment]
What happened here?

**Pull request closed without merging**
